# Generated by Django 5.1.7 on 2025-03-21 14:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
