# Generated by Django 5.1.7 on 2025-03-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appo', '0002_alter_advertisement_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='text',
            field=models.TextField(),
        ),
    ]
