# Generated by Django 5.1.7 on 2025-03-21 16:35

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appo', '0004_alter_advertisement_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
