# Generated by Django 5.1.7 on 2025-03-23 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appo', '0006_image_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='advertisement',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
