# Generated by Django 5.1.7 on 2025-03-24 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appo', '0007_remove_video_advertisement_delete_image_delete_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='advertisement_images/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='advertisement_videos/', verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='text',
            field=models.TextField(verbose_name='Текст объявления'),
        ),
    ]
