# Generated by Django 5.1.7 on 2025-03-24 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appo', '0009_advertisementimage_advertisementvideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='image',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='video',
        ),
    ]
