# Generated by Django 5.1.7 on 2025-04-02 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appo', '0011_onetimecode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OneTimeCode',
        ),
    ]
