# Generated by Django 5.1.7 on 2025-04-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appo', '0013_temporaryuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporaryuser',
            name='password',
            field=models.CharField(default=321456, max_length=128),
            preserve_default=False,
        ),
    ]
